In [24]:
name_list = []
label_list = []

In [25]:
def parsing(filename):
    f = open(filename, 'r')
    lines = f.readlines()
    lines[-1] += '\n'
    
    #print(type(lines))
    
    for line in lines:
        splited = line.split('\t')
        name_list.append(splited[0])
        label_list.append(splited[1])
    f.close()

    return name_list, label_list

In [26]:
parsing("test.txt")

(['audio/b020_90_100.wav',
  'audio/b020_110_120.wav',
  'audio/b020_100_110.wav',
  'audio/a071_90_100.wav',
  'audio/a071_10_20.wav',
  'audio/a071_20_30.wav',
  'audio/a126_230_240.wav',
  'audio/a126_220_230.wav',
  'audio/a126_210_220.wav',
  'audio/b097_90_100.wav',
  'audio/b097_110_120.wav',
  'audio/b097_100_110.wav',
  'audio/a131_130_140.wav',
  'audio/a131_120_130.wav',
  'audio/a131_140_150.wav',
  'audio/a043_90_100.wav',
  'audio/a043_110_120.wav',
  'audio/a043_100_110.wav',
  'audio/b085_160_170.wav',
  'audio/b085_170_180.wav',
  'audio/b085_150_160.wav',
  'audio/a038_30_40.wav',
  'audio/a038_40_50.wav',
  'audio/a038_50_60.wav'],
 ['beach\n',
  'beach\n',
  'beach\n',
  'bus\n',
  'bus\n',
  'bus\n',
  'cafe/restaurant\n',
  'cafe/restaurant\n',
  'cafe/restaurant\n',
  'car\n',
  'car\n',
  'car\n',
  'city_center\n',
  'city_center\n',
  'city_center\n',
  'forest_path\n',
  'forest_path\n',
  'forest_path\n',
  'grocery_store\n',
  'grocery_store\n',
  'grocery_

In [27]:
from sklearn.preprocessing import LabelBinarizer
lb = LabelBinarizer()

In [28]:
y = label_list

In [29]:
lb.fit(y)

LabelBinarizer(neg_label=0, pos_label=1, sparse_output=False)

In [30]:
lb.classes_

array(['beach\n', 'bus\n', 'cafe/restaurant\n', 'car\n', 'city_center\n',
       'forest_path\n', 'grocery_store\n', 'home\n'], 
      dtype='<U16')

In [38]:
onehot_label = lb.transform(y)
print(type(lb.transform(y)))
print(onehot_label)

<class 'numpy.ndarray'>
[[1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 1]]
